version: "3"

services:
  dev:
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    command: npx tailwindcss-cli@latest build /work/input/tailwind.css --minify --purge -c /work/input/tailwind.config.js -o /work/output/tailwind.css

  watch:
    build: .
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    tty: true            # docker run -t
    stdin_open: true     # docker run -i
    environment:
      - NODE_ENV=production
    command: /bin/sh /work/input/watch.sh

  prod:
    image: matiu/tailwind-yew-builder
    volumes:
      - ${INPUT:-./input}:/work/input
      - ${OUTPUT:-./output}:/work/output
      - ${SOURCE_CODE:-../}:/work/source_code
    environment:
      - NODE_ENV=production
    command: /bin/sh prod.sh

volumes:
  input:
  output:
  source_code:
